export const age = Array.from({ length: 62 }, (v, k) => k + 18);
export const sexuality = [
  "Any",
  "Hetero",
  "Homo",
  "Bi",
];
export const race = [
  "Any",
  "Caucasian",
  "Asian",
  "Black/African",
  "Mixed/Other",
  "Oriental",
  "Latino/Hispanic",
  "Middle eastern",
  "Native American",
];
export const eyeColor = [
  "Any",
  "Blue",
  "Brown",
  "Green",
  "Hazel",
  "Grey",
  "Other",
];
export const hairColor = [
  "Any",
  "Black",
  "Brown",
  "Red",
  "Blonde",
  "White",
  "Shaven/Bald",
  "Other",
];

export const data = [
  {
    "name": "Arianna",
    "age": "40",
    "sexuality": "Hetero",
    "race": "Oriental",
    "eyeColor": "Hazel",
    "hairColor": "Other",
    "photo": "assets/images/1.jpg",
  },
  {
    "name": "Natalie",
    "age": "42",
    "sexuality": "Hetero",
    "race": "Latino/Hispanic",
    "eyeColor": "Blue",
    "hairColor": "Black",
    "photo": "assets/images/2.jpg",
  },
  {
    "name": "Sophia",
    "age": "79",
    "sexuality": "Bi",
    "race": "Asian",
    "eyeColor": "Grey",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/3.jpg",
  },
  {
    "name": "Aria",
    "age": "26",
    "sexuality": "Hetero",
    "race": "Oriental",
    "eyeColor": "Green",
    "hairColor": "Other",
    "photo": "assets/images/4.jpg",
  },
  {
    "name": "Stella",
    "age": "66",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Grey",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/5.jpg",
  },
  {
    "name": "Mackenzie",
    "age": "59",
    "sexuality": "Homo",
    "race": "Asian",
    "eyeColor": "Brown",
    "hairColor": "Other",
    "photo": "assets/images/6.jpg",
  },
  {
    "name": "Kaitlyn",
    "age": "24",
    "sexuality": "Bi",
    "race": "Latino/Hispanic",
    "eyeColor": "Brown",
    "hairColor": "Red",
    "photo": "assets/images/7.jpg",
  },
  {
    "name": "Elizabeth",
    "age": "72",
    "sexuality": "Hetero",
    "race": "Black/African",
    "eyeColor": "Blue",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/8.jpg",
  },
  {
    "name": "Keira",
    "age": "52",
    "sexuality": "Homo",
    "race": "Oriental",
    "eyeColor": "Hazel",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/9.jpg",
  },
  {
    "name": "Sarah",
    "age": "22",
    "sexuality": "Bi",
    "race": "Black/African",
    "eyeColor": "Grey",
    "hairColor": "Black",
    "photo": "assets/images/10.jpg",
  },
  {
    "name": "Grace",
    "age": "42",
    "sexuality": "Homo",
    "race": "Black/African",
    "eyeColor": "Grey",
    "hairColor": "Other",
    "photo": "assets/images/11.jpg",
  },
  {
    "name": "Kylie",
    "age": "21",
    "sexuality": "Homo",
    "race": "Middle eastern",
    "eyeColor": "Grey",
    "hairColor": "Other",
    "photo": "assets/images/12.jpg",
  },
  {
    "name": "Allison",
    "age": "37",
    "sexuality": "Bi",
    "race": "Latino/Hispanic",
    "eyeColor": "Hazel",
    "hairColor": "Black",
    "photo": "assets/images/13.jpg",
  },
  {
    "name": "Gianna",
    "age": "45",
    "sexuality": "Homo",
    "race": "Mixed/Other",
    "eyeColor": "Hazel",
    "hairColor": "Other",
    "photo": "assets/images/14.jpg",
  },
  {
    "name": "Emma",
    "age": "19",
    "sexuality": "Hetero",
    "race": "Oriental",
    "eyeColor": "Blue",
    "hairColor": "Red",
    "photo": "assets/images/15.jpg",
  },
  {
    "name": "Victoria",
    "age": "77",
    "sexuality": "Bi",
    "race": "Latino/Hispanic",
    "eyeColor": "Hazel",
    "hairColor": "Black",
    "photo": "assets/images/16.jpg",
  },
  {
    "name": "Alexis",
    "age": "37",
    "sexuality": "Homo",
    "race": "Oriental",
    "eyeColor": "Green",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/17.jpg",
  },
  {
    "name": "Samantha",
    "age": "20",
    "sexuality": "Bi",
    "race": "Asian",
    "eyeColor": "Hazel",
    "hairColor": "Black",
    "photo": "assets/images/18.jpg",
  },
  {
    "name": "Victoria",
    "age": "19",
    "sexuality": "Hetero",
    "race": "Middle eastern",
    "eyeColor": "Green",
    "hairColor": "Other",
    "photo": "assets/images/19.jpg",
  },
  {
    "name": "Sarah",
    "age": "30",
    "sexuality": "Hetero",
    "race": "Caucasian",
    "eyeColor": "Grey",
    "hairColor": "Blonde",
    "photo": "assets/images/20.jpg",
  },
  {
    "name": "Keira",
    "age": "38",
    "sexuality": "Hetero",
    "race": "Middle eastern",
    "eyeColor": "Blue",
    "hairColor": "White",
    "photo": "assets/images/21.jpg",
  },
  {
    "name": "Peyton",
    "age": "41",
    "sexuality": "Homo",
    "race": "Black/African",
    "eyeColor": "Hazel",
    "hairColor": "Other",
    "photo": "assets/images/22.jpg",
  },
  {
    "name": "Amelia",
    "age": "51",
    "sexuality": "Homo",
    "race": "Caucasian",
    "eyeColor": "Brown",
    "hairColor": "Black",
    "photo": "assets/images/23.jpg",
  },
  {
    "name": "Scarlett",
    "age": "77",
    "sexuality": "Hetero",
    "race": "Caucasian",
    "eyeColor": "Grey",
    "hairColor": "Brown",
    "photo": "assets/images/24.jpg",
  },
  {
    "name": "Kaitlyn",
    "age": "35",
    "sexuality": "Homo",
    "race": "Native American",
    "eyeColor": "Grey",
    "hairColor": "Blonde",
    "photo": "assets/images/25.jpg",
  },
  {
    "name": "Maya",
    "age": "72",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Brown",
    "hairColor": "Other",
    "photo": "assets/images/26.jpg",
  },
  {
    "name": "Vivian",
    "age": "73",
    "sexuality": "Hetero",
    "race": "Middle eastern",
    "eyeColor": "Grey",
    "hairColor": "Black",
    "photo": "assets/images/27.jpg",
  },
  {
    "name": "Amelia",
    "age": "25",
    "sexuality": "Homo",
    "race": "Oriental",
    "eyeColor": "Green",
    "hairColor": "Red",
    "photo": "assets/images/28.jpg",
  },
  {
    "name": "Riley",
    "age": "20",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Brown",
    "hairColor": "Red",
    "photo": "assets/images/29.jpg",
  },
  {
    "name": "Violet",
    "age": "41",
    "sexuality": "Bi",
    "race": "Middle eastern",
    "eyeColor": "Grey",
    "hairColor": "Black",
    "photo": "assets/images/30.jpg",
  },
  {
    "name": "Sydney",
    "age": "21",
    "sexuality": "Hetero",
    "race": "Black/African",
    "eyeColor": "Brown",
    "hairColor": "White",
    "photo": "assets/images/31.jpg",
  },
  {
    "name": "Zoe",
    "age": "52",
    "sexuality": "Hetero",
    "race": "Oriental",
    "eyeColor": "Other",
    "hairColor": "Other",
    "photo": "assets/images/32.jpg",
  },
  {
    "name": "Scarlett",
    "age": "73",
    "sexuality": "Homo",
    "race": "Mixed/Other",
    "eyeColor": "Green",
    "hairColor": "Red",
    "photo": "assets/images/33.jpg",
  },
  {
    "name": "Makayla",
    "age": "32",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Other",
    "hairColor": "White",
    "photo": "assets/images/34.jpg",
  },
  {
    "name": "Sophia",
    "age": "27",
    "sexuality": "Hetero",
    "race": "Latino/Hispanic",
    "eyeColor": "Blue",
    "hairColor": "Brown",
    "photo": "assets/images/35.jpg",
  },
  {
    "name": "Lillian",
    "age": "78",
    "sexuality": "Hetero",
    "race": "Black/African",
    "eyeColor": "Brown",
    "hairColor": "Black",
    "photo": "assets/images/36.jpg",
  },
  {
    "name": "Katherine",
    "age": "53",
    "sexuality": "Bi",
    "race": "Asian",
    "eyeColor": "Hazel",
    "hairColor": "White",
    "photo": "assets/images/37.jpg",
  },
  {
    "name": "Kylie",
    "age": "71",
    "sexuality": "Bi",
    "race": "Latino/Hispanic",
    "eyeColor": "Hazel",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/38.jpg",
  },
  {
    "name": "Lucy",
    "age": "54",
    "sexuality": "Homo",
    "race": "Black/African",
    "eyeColor": "Hazel",
    "hairColor": "Red",
    "photo": "assets/images/39.jpg",
  },
  {
    "name": "Gabriella",
    "age": "35",
    "sexuality": "Bi",
    "race": "Native American",
    "eyeColor": "Grey",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/40.jpg",
  },
  {
    "name": "Elena",
    "age": "34",
    "sexuality": "Hetero",
    "race": "Asian",
    "eyeColor": "Hazel",
    "hairColor": "Black",
    "photo": "assets/images/41.jpg",
  },
  {
    "name": "Charlotte",
    "age": "39",
    "sexuality": "Hetero",
    "race": "Middle eastern",
    "eyeColor": "Brown",
    "hairColor": "Brown",
    "photo": "assets/images/42.jpg",
  },
  {
    "name": "Savannah",
    "age": "67",
    "sexuality": "Hetero",
    "race": "Black/African",
    "eyeColor": "Green",
    "hairColor": "Red",
    "photo": "assets/images/43.jpg",
  },
  {
    "name": "Chloe",
    "age": "37",
    "sexuality": "Bi",
    "race": "Mixed/Other",
    "eyeColor": "Brown",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/44.jpg",
  },
  {
    "name": "Liliana",
    "age": "27",
    "sexuality": "Hetero",
    "race": "Latino/Hispanic",
    "eyeColor": "Green",
    "hairColor": "White",
    "photo": "assets/images/45.jpg",
  },
  {
    "name": "Layla",
    "age": "27",
    "sexuality": "Hetero",
    "race": "Oriental",
    "eyeColor": "Other",
    "hairColor": "Black",
    "photo": "assets/images/46.jpg",
  },
  {
    "name": "Gabriella",
    "age": "64",
    "sexuality": "Bi",
    "race": "Mixed/Other",
    "eyeColor": "Blue",
    "hairColor": "Red",
    "photo": "assets/images/47.jpg",
  },
  {
    "name": "Alaina",
    "age": "67",
    "sexuality": "Bi",
    "race": "Middle eastern",
    "eyeColor": "Other",
    "hairColor": "Brown",
    "photo": "assets/images/48.jpg",
  },
  {
    "name": "Evelyn",
    "age": "18",
    "sexuality": "Bi",
    "race": "Latino/Hispanic",
    "eyeColor": "Hazel",
    "hairColor": "Black",
    "photo": "assets/images/49.jpg",
  },
  {
    "name": "Audrey",
    "age": "58",
    "sexuality": "Homo",
    "race": "Asian",
    "eyeColor": "Green",
    "hairColor": "Other",
    "photo": "assets/images/50.jpg",
  },
  {
    "name": "Adalyn",
    "age": "77",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Blue",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/51.jpg",
  },
  {
    "name": "Zoe",
    "age": "65",
    "sexuality": "Bi",
    "race": "Mixed/Other",
    "eyeColor": "Green",
    "hairColor": "Other",
    "photo": "assets/images/52.jpg",
  },
  {
    "name": "Alexis",
    "age": "56",
    "sexuality": "Bi",
    "race": "Native American",
    "eyeColor": "Green",
    "hairColor": "Black",
    "photo": "assets/images/53.jpg",
  },
  {
    "name": "Adeline",
    "age": "32",
    "sexuality": "Homo",
    "race": "Black/African",
    "eyeColor": "Green",
    "hairColor": "Brown",
    "photo": "assets/images/54.jpg",
  },
  {
    "name": "Jasmine",
    "age": "36",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Other",
    "hairColor": "Blonde",
    "photo": "assets/images/55.jpg",
  },
  {
    "name": "Caroline",
    "age": "66",
    "sexuality": "Homo",
    "race": "Caucasian",
    "eyeColor": "Blue",
    "hairColor": "Brown",
    "photo": "assets/images/56.jpg",
  },
  {
    "name": "Brooklyn",
    "age": "64",
    "sexuality": "Homo",
    "race": "Mixed/Other",
    "eyeColor": "Green",
    "hairColor": "Brown",
    "photo": "assets/images/57.jpg",
  },
  {
    "name": "Stella",
    "age": "48",
    "sexuality": "Bi",
    "race": "Mixed/Other",
    "eyeColor": "Grey",
    "hairColor": "Brown",
    "photo": "assets/images/58.jpg",
  },
  {
    "name": "Olivia",
    "age": "62",
    "sexuality": "Bi",
    "race": "Asian",
    "eyeColor": "Green",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/59.jpg",
  },
  {
    "name": "Makayla",
    "age": "52",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Grey",
    "hairColor": "Other",
    "photo": "assets/images/60.jpg",
  },
  {
    "name": "Gianna",
    "age": "66",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Green",
    "hairColor": "Other",
    "photo": "assets/images/61.jpg",
  },
  {
    "name": "Abigail",
    "age": "47",
    "sexuality": "Bi",
    "race": "Oriental",
    "eyeColor": "Green",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/62.jpg",
  },
  {
    "name": "Camilla",
    "age": "57",
    "sexuality": "Homo",
    "race": "Black/African",
    "eyeColor": "Blue",
    "hairColor": "Black",
    "photo": "assets/images/63.jpg",
  },
  {
    "name": "Paisley",
    "age": "72",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Other",
    "hairColor": "Other",
    "photo": "assets/images/64.jpg",
  },
  {
    "name": "Avery",
    "age": "63",
    "sexuality": "Bi",
    "race": "Oriental",
    "eyeColor": "Blue",
    "hairColor": "Brown",
    "photo": "assets/images/65.jpg",
  },
  {
    "name": "Alyssa",
    "age": "71",
    "sexuality": "Homo",
    "race": "Native American",
    "eyeColor": "Grey",
    "hairColor": "Brown",
    "photo": "assets/images/66.jpg",
  },
  {
    "name": "Eva",
    "age": "25",
    "sexuality": "Bi",
    "race": "Native American",
    "eyeColor": "Green",
    "hairColor": "Blonde",
    "photo": "assets/images/67.jpg",
  },
  {
    "name": "Mia",
    "age": "53",
    "sexuality": "Homo",
    "race": "Caucasian",
    "eyeColor": "Other",
    "hairColor": "Brown",
    "photo": "assets/images/68.jpg",
  },
  {
    "name": "Olivia",
    "age": "49",
    "sexuality": "Homo",
    "race": "Black/African",
    "eyeColor": "Blue",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/69.jpg",
  },
  {
    "name": "Maya",
    "age": "77",
    "sexuality": "Hetero",
    "race": "Asian",
    "eyeColor": "Brown",
    "hairColor": "Red",
    "photo": "assets/images/70.jpg",
  },
  {
    "name": "Arianna",
    "age": "40",
    "sexuality": "Bi",
    "race": "Mixed/Other",
    "eyeColor": "Grey",
    "hairColor": "Black",
    "photo": "assets/images/71.jpg",
  },
  {
    "name": "Sydney",
    "age": "64",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Grey",
    "hairColor": "White",
    "photo": "assets/images/72.jpg",
  },
  {
    "name": "Mia",
    "age": "53",
    "sexuality": "Hetero",
    "race": "Middle eastern",
    "eyeColor": "Blue",
    "hairColor": "Red",
    "photo": "assets/images/73.jpg",
  },
  {
    "name": "Madison",
    "age": "27",
    "sexuality": "Hetero",
    "race": "Latino/Hispanic",
    "eyeColor": "Hazel",
    "hairColor": "Other",
    "photo": "assets/images/74.jpg",
  },
  {
    "name": "Clara",
    "age": "74",
    "sexuality": "Bi",
    "race": "Caucasian",
    "eyeColor": "Green",
    "hairColor": "Brown",
    "photo": "assets/images/75.jpg",
  },
  {
    "name": "Kayla",
    "age": "52",
    "sexuality": "Hetero",
    "race": "Mixed/Other",
    "eyeColor": "Blue",
    "hairColor": "Red",
    "photo": "assets/images/76.jpg",
  },
  {
    "name": "Peyton",
    "age": "54",
    "sexuality": "Bi",
    "race": "Middle eastern",
    "eyeColor": "Hazel",
    "hairColor": "Red",
    "photo": "assets/images/77.jpg",
  },
  {
    "name": "Ella",
    "age": "67",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Brown",
    "hairColor": "Other",
    "photo": "assets/images/78.jpg",
  },
  {
    "name": "Annabelle",
    "age": "53",
    "sexuality": "Homo",
    "race": "Mixed/Other",
    "eyeColor": "Brown",
    "hairColor": "Brown",
    "photo": "assets/images/79.jpg",
  },
  {
    "name": "Paisley",
    "age": "26",
    "sexuality": "Hetero",
    "race": "Mixed/Other",
    "eyeColor": "Blue",
    "hairColor": "Black",
    "photo": "assets/images/80.jpg",
  },
  {
    "name": "Mila",
    "age": "40",
    "sexuality": "Bi",
    "race": "Caucasian",
    "eyeColor": "Brown",
    "hairColor": "Black",
    "photo": "assets/images/81.jpg",
  },
  {
    "name": "Bailey",
    "age": "64",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Blue",
    "hairColor": "Blonde",
    "photo": "assets/images/82.jpg",
  },
  {
    "name": "Kaitlyn",
    "age": "32",
    "sexuality": "Bi",
    "race": "Middle eastern",
    "eyeColor": "Blue",
    "hairColor": "Blonde",
    "photo": "assets/images/83.jpg",
  },
  {
    "name": "Samantha",
    "age": "58",
    "sexuality": "Bi",
    "race": "Middle eastern",
    "eyeColor": "Other",
    "hairColor": "White",
    "photo": "assets/images/84.jpg",
  },
  {
    "name": "Hailey",
    "age": "18",
    "sexuality": "Homo",
    "race": "Native American",
    "eyeColor": "Brown",
    "hairColor": "Red",
    "photo": "assets/images/85.jpg",
  },
  {
    "name": "Lillian",
    "age": "37",
    "sexuality": "Hetero",
    "race": "Native American",
    "eyeColor": "Blue",
    "hairColor": "Other",
    "photo": "assets/images/86.jpg",
  },
  {
    "name": "Vivian",
    "age": "46",
    "sexuality": "Bi",
    "race": "Middle eastern",
    "eyeColor": "Blue",
    "hairColor": "Black",
    "photo": "assets/images/87.jpg",
  },
  {
    "name": "Harper",
    "age": "45",
    "sexuality": "Hetero",
    "race": "Latino/Hispanic",
    "eyeColor": "Grey",
    "hairColor": "Black",
    "photo": "assets/images/88.jpg",
  },
  {
    "name": "Evelyn",
    "age": "65",
    "sexuality": "Bi",
    "race": "Black/African",
    "eyeColor": "Hazel",
    "hairColor": "Black",
    "photo": "assets/images/89.jpg",
  },
  {
    "name": "Aria",
    "age": "38",
    "sexuality": "Bi",
    "race": "Asian",
    "eyeColor": "Other",
    "hairColor": "Brown",
    "photo": "assets/images/90.jpg",
  },
  {
    "name": "Samantha",
    "age": "56",
    "sexuality": "Homo",
    "race": "Asian",
    "eyeColor": "Brown",
    "hairColor": "White",
    "photo": "assets/images/91.jpg",
  },
  {
    "name": "Makayla",
    "age": "75",
    "sexuality": "Bi",
    "race": "Oriental",
    "eyeColor": "Blue",
    "hairColor": "Red",
    "photo": "assets/images/92.jpg",
  },
  {
    "name": "Lucy",
    "age": "26",
    "sexuality": "Bi",
    "race": "Oriental",
    "eyeColor": "Blue",
    "hairColor": "Black",
    "photo": "assets/images/93.jpg",
  },
  {
    "name": "Abigail",
    "age": "75",
    "sexuality": "Hetero",
    "race": "Black/African",
    "eyeColor": "Green",
    "hairColor": "Blonde",
    "photo": "assets/images/94.jpg",
  },
  {
    "name": "Mackenzie",
    "age": "74",
    "sexuality": "Hetero",
    "race": "Latino/Hispanic",
    "eyeColor": "Hazel",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/95.jpg",
  },
  {
    "name": "Alaina",
    "age": "40",
    "sexuality": "Bi",
    "race": "Mixed/Other",
    "eyeColor": "Blue",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/96.jpg",
  },
  {
    "name": "Gianna",
    "age": "54",
    "sexuality": "Bi",
    "race": "Caucasian",
    "eyeColor": "Green",
    "hairColor": "Shaven/Bald",
    "photo": "assets/images/97.jpg",
  },
  {
    "name": "Caroline",
    "age": "27",
    "sexuality": "Bi",
    "race": "Oriental",
    "eyeColor": "Brown",
    "hairColor": "Black",
    "photo": "assets/images/98.jpg",
  },
  {
    "name": "Makayla",
    "age": "50",
    "sexuality": "Homo",
    "race": "Latino/Hispanic",
    "eyeColor": "Green",
    "hairColor": "Red",
    "photo": "assets/images/99.jpg",
  },
  {
    "name": "Reagan",
    "age": "24",
    "sexuality": "Hetero",
    "race": "Mixed/Other",
    "eyeColor": "Other",
    "hairColor": "White",
    "photo": "assets/images/100.jpg",
  },
]
